
services:
  frontend:
    image: ghcr.io/danielatanasovski/led-clock-frontend:latest
    ports:
      - "3000:3000"
    restart: always
    networks:
      bridge:
        aliases:
          - frontend
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    deploy:
      update_config:
        parallelism: 2
        delay: 10s
        failure_action: rollback
    environment:
      - LED_SERVER_URL=https://led.atanasovski.xyz

networks:
  bridge:
    name: led-clock-network
    driver: bridge
